const appname = "eMart Seller App",
    login = "Login",
    welcome = "Hi, Welcome to",
    email = "Email",
    password = "Password",
    forgotPassword = "Forgot Password",
    anyProblem = "In case of any difficulty, contact administration",
    emailHint = "eg. vendor@emart.com",
    passwordHint = "* * * * * *",
    dashboard = "Dashboard",
    rating = "Rating",
    shopSettings = "Shop Settings",
    messages = "Messages",
    logout = "Logout",
    unpaid = "Unpaid",
    totalSales = "Total Sales",
    popular = "Popular Product",
    orders = "Orders",
    loginTo = "Login to your account",
    products = "Products",
    settings = "Settings",
    featured = "Featured",
    edit = "Edit",
    remove = "Remove",
    save = "Save",
    name = "Username",
    chats = "Chats",
    confirmPass = "Confirm Password",
    changeImage = "Change Image",
    editProfile = "Edit Profile",
    credit = "@BaabaDevs";


    //shop settings strings

    const nameHint = "eg. Vendor Name",
    shopDescHint = "Enter your shop description",
    shopWebsiteHint = "eg. vendor.emart.com",
    shopMobileHint = "eg. +84645387685",
    shopAddressHint = "eg. Da Nang",
    description = "Description",
    mobile = "Shop Mobile",
    website = "Shop Website",
    shopName = "Shop Name",
    adress = "shop Address";
